<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<RootNamespace>ShutUp11</RootNamespace>
		<AssemblyName>ShutUp11</AssemblyName>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>logo\logo.ico</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
		<Resource Include="logo\logo.png" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
		<PackageReference Include="System.Management" Version="8.0.0" />
	</ItemGroup>
</Project>